from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from datetime import datetime, timezone
from app.auth import create_access_token, get_current_user
from app.database import get_db
from app.models.all_models import User, TelegramSession
from app.schemas.all_schemas import LoginResponse, UserOut
from pydantic import BaseModel

router = APIRouter(prefix="/api/auth", tags=["auth"])


class TelegramLoginRequest(BaseModel):
    code: str


@router.post("/telegram", response_model=LoginResponse)
async def telegram_login(data: TelegramLoginRequest, db: AsyncSession = Depends(get_db)):
    """Login via Telegram code generated by /start command."""
    code = data.code.strip().upper()
    if not code or len(code) < 8:
        raise HTTPException(status.HTTP_400_BAD_REQUEST, "Invalid code format")

    result = await db.execute(
        select(TelegramSession).where(TelegramSession.login_code == code)
    )
    ts = result.scalar_one_or_none()
    if not ts:
        raise HTTPException(status.HTTP_401_UNAUTHORIZED, "Invalid or expired code")

    if ts.login_code_expires and ts.login_code_expires < datetime.now(timezone.utc):
        raise HTTPException(status.HTTP_401_UNAUTHORIZED, "Code expired. Run /start again.")

    user_result = await db.execute(select(User).where(User.id == ts.user_id))
    user = user_result.scalar_one_or_none()
    if not user:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "User not found")
    if user.is_banned:
        raise HTTPException(status.HTTP_403_FORBIDDEN, "Account banned")

    # Invalidate code (single use)
    ts.login_code = None
    ts.login_code_expires = None
    await db.commit()

    return LoginResponse(
        access_token=create_access_token(user.id, user.role),
        user_id=str(user.id),
        role=user.role,
    )


@router.get("/me", response_model=UserOut)
async def me(current_user: User = Depends(get_current_user)):
    return UserOut.model_validate(current_user)
